trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

resources:
  repositories:
    - repository: rust_pipelines
      type: github
      name: xoac/rust-azure-pipelines
      ref: refs/tags/v0.0.3
      endpoint: github.com_reynn

stages:
- stage: check
  displayName: "Quick checks"
  jobs:
  - template: ci/jobs/cargo-check.yml@rust_pipelines

- stage: test
  displayName: "Clippy"
  jobs:
  - template: ci/jobs/cargo-clippy.yml@rust_pipelines
    parameters:
      min_rust_supported: 1.42

