[package]
name = "manager"
version = "0.1.0"
authors = ["Nic Patterson <nic@reynn.dev>"]
edition = "2018"

[dependencies]
error-chain = { version = "0.12" }
clap = {version = "3.0.0-beta.1"}
tokio = { version = "0.2", features = ["full"] }
core = { path = "../core" }
